---
- hosts: all
  vars:
    iso_filename: 'CentOS-7-x86_64-Everything-1611.iso'
    iso_location: 'http://10.1.1.254/repos/centos/7/isos/x86_64/'
    iso_checksum: 'af4969ebbdc479d330de97c5bfbb37eedc64c369f009cb15a97f9553ba441c88'
    iso_checksum_algo: 'sha256'
    centiso_var: "/var/centiso"
    workspace: "{{ ansible_user_dir }}/centiso"
    build_root: "{{ centiso_var }}/iso_build_root"
  tasks:
  - name: Ensure packages needed to build the ISO image are installed
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - genisoimage
      - createrepo
    become: yes
  - name: Ensure directories for building the new ISO image exist
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ centiso_var }}"
      - "{{ centiso_var }}/CustomRPMs"
      - "{{ workspace }}"
      - "{{ workspace }}/files"
      - "{{ build_root }}"
      - "{{ build_root }}/isolinux"
      - "{{ build_root }}/isolinux/images"
      - "{{ build_root }}/isolinux/images/pxeboot"
      - "{{ build_root }}/isolinux/ks"
      - "{{ build_root }}/isolinux/LiveOS"
      - "{{ build_root }}/isolinux/Packages"
      - "{{ build_root }}/isolinux/CustomRPMs"
      - "{{ build_root }}/utils"
      - "{{ build_root }}/mnt"
  - name: Ensure we have an ISO image to use as a starting point
    get_url:
      url: "{{ iso_location }}/{{ iso_filename }}"
      dest: "{{ centiso_var }}/{{ iso_filename }}"
      checksum: "{{ iso_checksum_algo }}:{{ iso_checksum }}"
  - name: Ensure the original ISO image is mounted
    mount:
      src: "{{ centiso_var }}/{{ iso_filename }}"
      path: "{{ build_root }}/mnt"
      state: mounted
      fstype: iso9660
      opts: loop,ro
    become: yes
  - name: Ensure necessary files have been copied to destination directories
    synchronize:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      - { src: '{{ build_root }}/mnt/isolinux/', dest: '{{ build_root }}/isolinux/' }
      - { src: '{{ build_root }}/mnt/images/', dest: '{{ build_root }}/isolinux/images/' }
      - { src: '{{ build_root }}/mnt/LiveOS/', dest: '{{ build_root }}/isolinux/LiveOS/' }
      - { src: '{{ build_root }}/mnt/.discinfo', dest: '{{ build_root }}/isolinux/' }
  - name: Ensure RPMs from original media are copied to destination Packages directory
    synchronize:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      - { src: '{{ build_root }}/mnt/Packages/', dest: '{{ build_root }}/isolinux/Packages/' }
  - name: Ensure additional RPMs are copied from workspace share to the destination CustomRPMs directory
    synchronize:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      - { src: '{{ centiso_var }}/CustomRPMs/', dest: '{{ build_root }}/isolinux/CustomRPMs/' }
  - name: Ensure the chefdk RPM has been downloaded
    get_url:
      url: "https://packages.chef.io/files/stable/chefdk/1.4.3/el/7/chefdk-1.4.3-1.el7.x86_64.rpm"
      dest: "{{ build_root }}/isolinux/CustomRPMs/chefdk-1.4.3-1.el7.x86_64.rpm"
      checksum: "sha256:bb70be05a6a99071d26ec288d338459fe71fdd6ab0e4cbb661ae66dfb6c82fc5"
  - name: Ensure the repodata has been updated
    command: "createrepo -g {{ build_root }}/mnt/repodata/d918936f5019be3fb66e9981a28cb2a41477a2963d741d454f79377a22214f43-c7-x86_64-comps.xml ."
    args:
      chdir: "{{ build_root }}/isolinux"
  - name: Ensure the kickstart files have been copied to the new ISO directories
    copy:
      src: "{{ workspace }}/files/{{ item }}"
      dest: "{{ build_root }}/isolinux/ks/{{ item }}"
    with_items:
      - ks.cfg
      - workstation-ks.cfg
  - name: Ensure isolinux.cfg is customized
    copy:
      src: "{{ workspace }}/files/isolinux.cfg"
      dest: '{{ build_root }}/isolinux/isolinux.cfg'
  - name: Ensure a new ISO image is created from the destination directory
    command: genisoimage -untranslated-filenames -V 'CentOS 7 x86_64' -J -joliet-long -rational-rock -translation-table -input-charset utf-8 -x ./lost+found -b isolinux.bin -c boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -eltorito-alt-boot -e images/efiboot.img -no-emul-boot -o "{{ centiso_var }}/CentOS-7-x86_64-Custom.iso" -T isolinux/
    args:
      chdir: "{{ build_root }}"
